image:
  repository: galaxyproject/galaxy-min
  tag: 22.05
postgresql:
  galaxyDatabasePassword: galaxydbpassword
  persistence:
    storageClass: nfs
ingress:
  canary:
    enabled: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  path: "/"
  hosts:
    - host: ~
      paths:
        - path: "/"
cvmfs:
  enabled: false
  deploy: false
  cache:
    alienCache:
      storageClass: nfs
persistence:
  accessMode: ReadWriteMany
  storageClass: nfs
  size: 300Gi
initJob:
  downloadToolConfs:
    enabled: true
webHandlers:
  startupDelay: 10
jobHandlers:
  startupDelay: 5
workflowHandlers:
  startupDelay: 0
configs:
  galaxy.yml:
    galaxy:
      job_metrics_config_file: job_metrics_conf.yml
      admin_users: "afgane@gmail.com,suderman@jhu.edu"
      master_api_key: galaxypassword
      brand: M6I
  job_metrics_conf.yml:
    - type: core
    - type: cgroup
    - type: cpuinfo
    - type: meminfo
    - type: uname
jobs:
  rules:
    tpv_rules_local.yml:
      tools:
        default:
          scheduling:
            reject:
            - local
            - offline
      destinations:
        local:
          scheduling:
            require:
            - local            
rabbitmq:
  persistence:
    storageClassName: gp2