---
- hosts: localhost
  # ansible-galaxy collection install kubernetes.core
  collections:
    - kubernetes.core
  tasks:
    #
    # Add Helm repositories
    #
    # - name: Add Helm repositories
    #   helm_repository:
    #     name: "{{ item.name }}"
    #     repo_url: "{{ item.repo_url }}"
    #     state: present
    #   loop:
    #     - name: aws-ebs-csi-driver
    #       repo_url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    #     - name: ingress-nginx
    #       repo_url: https://kubernetes.github.io/ingress-nginx
    #     - name: stable
    #       repo_url: https://charts.helm.sh/stable
    #     - name: galaxy 
    #       repo_url: https://raw.githubusercontent.com/CloudVE/helm-charts/master/
    #     - name: ksuderman
    #       repo_url: https://ksuderman.github.io/helm_charts

    # Create namespaces
    #
    - name: Create the namespaces
      k8s:
        kind: Namespace 
        name: "{{ item }}"
        state: present 
      loop:
        - ingress-nginx
        - csi-drivers
        - galaxy
    #
    # Install packages
    # - name: Install Nginx Ingress
    #   helm:
    #     name: ingress-nginx
    #     namespace: ingress-nginx
    #     chart_ref: ingress-nginx/ingress-nginx
    #     chart_version: 3.34.0
    #     values:
    #       controller:
    #         kind: "DaemonSet"
    #         hostNetwork: true
    #         daemonset:
    #           useHostPort: true 
    - name: Install EBS Storage Class 
      k8s: 
        src: files/ebs_storage_class.yml
        state: present 
    - name: Install EBS CSI drivers
      helm: 
        name: aws-ebs-csi-driver
        namespace: csi-drivers
        chart_ref: aws-ebs-csi-driver/aws-ebs-csi-driver
        values:
          enableVolumeScheduling: true
          enableVolumeResizing: true 
          enableVolumeSnapshot: true
    - name: Install NFS Provisioner
      helm:
        name: nfs-provisioner
        namespace: csi-drivers
        chart_ref: nfs-ganesha/nfs-server-provisioner
        values:
          peristence:
            enabled: true
            storageClass: ebs 
            size: "525Gi"
          storageClass:
            create: true 
            reclaimPolicy: Delete
            allowVolumeExpansion: true
    # - name: Install Galaxy
    #   helm:
    #     name: galaxy
    #     namespace: galaxy
    #     chart_ref: galaxy/galaxy
    #     values_files: files/values.yml




