---
- hosts: localhost
  # ansible-galaxy collection install kubernetes.core
  collections:
    - kubernetes.core
  tasks:
    #
    # Add Helm repositories
    #
    - name: Add Helm repository for Nginx ingress
      helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx
        state: present 
    - name: Add stable Helm repository 
      helm_repository:
        name: stable
        repo_url: https://charts.helm.sh/stable
        state: present
    - name: Add Galaxy Helm repo
      helm_repository:
        name: galaxy 
        repo_url: https://raw.githubusercontent.com/CloudVE/helm-charts/master/
        state: present 
    #
    # Create namespaces
    #
    - name: Create the namespace for Nginx
      k8s:
        kind: Namespace 
        name: ingress-nginx
        state: present 
    - name: Create the namespace for the CSI drivers
      k8s:
        kind: Namespace 
        name: csi-drivers
        state: present 
    - name: Create Galaxy namespace
      k8s: 
        kind: Namespace
        name: galaxy
        state: present 
    #
    # Install packages
    - name: Install Nginx Ingress
      helm:
        name: ingress-nginx
        namespace: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        chart_version: 3.34.0
        values:
          controller:
            kind: "DaemonSet"
            hostNetwork: true
            daemonset:
              useHostPort: true 
    - name: Install EBS Storage Class 
      k8s: 
        src: files/ebs_storage_class.yml
        state: present 
    - name: Install EBS CSI drivers
      helm: 
        name: aws-ebs-csi-driver
        namespace: csi-drivers
        chart_ref: charts/aws-ebs-csi-drivers.tgz
        values:
          enableVolumeScheduling: true
          enableVolumeResizing: true 
          enableVolumeSnapshot: true
    - name: Install NFS Provisioner
      helm:
        name: nfs-provisioner
        namespace: csi-drivers
        chart_ref: stable/nfs-server-provisioner
        values:
          peristence:
            enabled: true
            storageClass: ebs 
            size: "501Gi"
          storageClass:
            create: true 
            reclaimPolicy: Delete
            allowVolumeExpansion: true
    - name: Install Galaxy
      helm:
        name: galaxy
        namespace: galaxy
        chart_ref: galaxy/galaxy
        values_files: files/values.yml




