# Install eksctl and use with:
# eksctl create cluster -f build_aws_cluster.yaml --profile cost-modeling

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bench
  region: us-east-1
  version: '1.19'

managedNodeGroups:
  - name: master
    ami: ami-070e4812804b3c418  # Official Ubuntu image for EKS
    instanceType: m5a.2xlarge
    minSize: 1
    maxSize: 1
    volumeSize: 99
    ssh:
      allow: true
      publicKeyName: cloudman_key_pair
    labels: {role: master}
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        ebs: true
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh ea-cluster --container-runtime containerd
      sudo apt-get update && sudo apt-get install -y nfs-common

  - name: workers
    ami: ami-070e4812804b3c418
    instanceType: m5a.8xlarge
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    volumeSize: 101
    iam:
      withAddonPolicies:
        ebs: true
    labels: {role: worker}
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh ea-cluster --container-runtime containerd
      sudo apt-get update && sudo apt-get install -y nfs-common
