configs:
  galaxy.yml:
    galaxy:
      admin_users: afgane@gmail.com,suderman@jhu.edu
      job_metrics_config_file: job_metrics_conf.yml
      master_api_key: galaxypassword
  job_metrics_conf.yml:
  - type: core
  - type: cgroup
  - type: cpuinfo
  - type: meminfo
  - type: uname
cvmfs:
  enable: false
  deploy: false
image:
  repository: galaxyproject/galaxy-min
  tag: 22.05
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: false
  canary:
    enabled: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: ~
    paths:
    - path: /galaxy
  path: /galaxy
initJob:
  downloadToolConfs:
    enabled: true
jobHandlers:
  startupDelay: 5
persistence:
  accessMode: ReadWriteMany
  size: 400Gi
  storageClass: nfs
postgresql:
  galaxyDatabasePassword: galaxydbpassword
  persistence:
    storageClass: nfs
webHandlers:
  startupDelay: 10
workflowHandlers:
  startupDelay: 0
resources:
  limits:
    cpu: 3
    memory: 16G
    ephemeral-storage: 64Gi
