apiVersion: v1
kind: ResourceQuota
metadata:
  name: gcp-critical-pods
  namespace: galaxy
spec:
  hard:
    pods: 1G
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
      - system-cluster-critical
