jobs:
  rules:
    container_mapper_rules.yml:
      resources:
        resource_sets:
          small:
            requests:
              cpu: '15'
              memory: 63G
            limits:
              cpu: '15'
              memory: 63G
          medium:
            requests:
              cpu: '15'
              memory: 63G
            limits:
              cpu: '15'
              memory: 63G
          large:
            requests:
              cpu: '15'
              memory: 63G
            limits:
              cpu: '15'
              memory: 63G
          2xlarge:
            requests:
              cpu: '15'
              memory: 63G
            limits:
              cpu: '15'
              memory: 63G
          mlarge:
            requests:
              cpu: '15'
              memory: 63G
            limits:
              cpu: '15'
              memory: 63G
        default_resource_set: small
